services:
  auth-postgres:
    image: postgres:16-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_USER: fitcore
      POSTGRES_PASSWORD: fitcore123
      POSTGRES_DB: fitcore_auth
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

volumes:
  auth_postgres_data: