CREATE TABLE RUOLO(
    ID_ROLE UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    NOME VARCHAR(55) NOT NULL
);

create table USER_ACCOUNT (
    ACCOUNT_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USERNAME VARCHAR(55) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ID_RUOLO UUID REFERENCES RUOLO(ID_ROLE),
    DATA_REGISTRAZIONE TIMESTAMP NOT NULL DEFAULT now(),
    IS_ACTIVE BOOLEAN
);

CREATE TABLE PERMESSI(
    ID_PERMESSO UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CODICE VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL
);

CREATE TABLE RUOLO_PERMESSI(
    ID_RUOLO UUID REFERENCES ruolo(id_role),
    ID_PERMESSO UUID REFERENCES permessi(id_permesso),
    PRIMARY KEY (ID_RUOLO, ID_PERMESSO)
);